


FROM changhui/ubuntu:20.04-base
USER root





COPY ./src/ubuntu/install/jetbrains $STARTUPDIR
# Install startup
RUN  bash $STARTUPDIR/download_idea.sh
RUN  bash $STARTUPDIR/install_idea.sh




USER 1000
