
FROM changhui/ubuntu:20.04-ide as builder

FROM changhui/ubuntu:20.04-base
USER root



# copy idea
RUN --mount=type=bind,from=builder,source=/home/kasm-user,target=/tmp \
cd /tmp \
&& cp -r --path Desktop/*.desktop  .config/JetBrains .cache/JetBrains .java .jdks .local/share/JetBrains /home/kasm-user \
&&  chown -R 1000:0 $HOME 

RUN --mount=type=bind,from=builder,source=/usr/share,target=/tmp \
cd /tmp \
&& cp -r --path    clion-2022.2.4 activate_files activate.html jetbra /usr/share/   

 
RUN --mount=type=bind,from=builder,source=/usr/share,target=/tmp \
cd /tmp \
&& cp  -r --path  idea-IU-222.4459.24 /usr/share/ \ 
&& ln -s $HOME/.config /root/.config




USER 1000
