FROM ubuntu:jammy
USER root

WORKDIR /root
COPY ./src/ubuntu/install/vs_code $INST_SCRIPTS/vs_code/
RUN bash $INST_SCRIPTS/vs_code/install_package.sh  
 RUN bash $INST_SCRIPTS/vs_code/install_vs_code_web.sh  \
 && rm -rf $INST_SCRIPTS/vs_code/


# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
######## End cuda #####################



 




