

FROM kasmweb/core-ubuntu-focal:develop
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME
######### Install docker ###########

RUN sed -i 's/ubuntu-mono-dark/elementary-xfce/g' $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml


# COPY ./src/ubuntu/install/dind $INST_SCRIPTS/dind


# RUN mkdir -p  /etc/docker  &&  mv $INST_SCRIPTS/dind/daemon.json /etc/docker/daemon.json \
# && mv  $INST_SCRIPTS/dind/custom_startup.sh  $STARTUPDIR/custom_startup.sh \
# &&  chmod +x $STARTUPDIR/custom_startup.sh &&  chmod 755 $STARTUPDIR/custom_startup.sh \
# && bash $INST_SCRIPTS/dind/install_dind.sh  && rm -rf $INST_SCRIPTS/dind/

# VOLUME /var/lib/docker



# Add Kasm Branding
#RUN cp /usr/share/extra/backgrounds/bg_kasm.png /usr/share/extra/backgrounds/bg_default.png
#RUN cp /usr/share/extra/icons/icon_kasm.png /usr/share/extra/icons/icon_default.png


# Install Custom Certificate Authority
# COPY ./src/ubuntu/install/certificates $INST_SCRIPTS/certificates/
# RUN bash $INST_SCRIPTS/certificates/install_ca_cert.sh && rm -rf $INST_SCRIPTS/certificates/
# Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/





# COPY ./src/ubuntu/install/puppeteer $INST_SCRIPTS/puppeteer/
# RUN bash $INST_SCRIPTS/puppeteer/install_puppeteer.sh  && rm -rf $INST_SCRIPTS/puppeteer/

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all
######## End cuda #####################


 
 

COPY ./src/ubuntu/install/openlens $INST_SCRIPTS/openlens/
RUN bash $INST_SCRIPTS/openlens/install_openlens.sh \
rm -rf $INST_SCRIPTS/openlens/ 

COPY ./src/ubuntu/install/copyq $INST_SCRIPTS/copyq/
RUN bash $INST_SCRIPTS/copyq/install.sh \
rm -rf $INST_SCRIPTS/copyq/

COPY  ./src/ubuntu/install/vs_code $INST_SCRIPTS/vs_code/ 
RUN bash $INST_SCRIPTS/vs_code/install_package.sh 
RUN bash $INST_SCRIPTS/vs_code/install_vs_code_web.sh \
rm -rf $INST_SCRIPTS/vs_code/ 

COPY ./src/ubuntu/install/startup $STARTUPDIR
# Install startup
RUN  bash $STARTUPDIR/install_tools.sh
RUN  bash $STARTUPDIR/install_startup.sh 
RUN bash $STARTUPDIR/install_ca_cert.sh



 

ENV HOME /home/kasm-user
USER 1000


