
FROM changhui/ubuntu:20.04-ide as builder

FROM changhui/ubuntu:20.04-base
USER root



# copy idea

COPY ./src/ubuntu/install/jetbrains/download_clion.sh $INST_SCRIPTS
# Install startup
RUN  bash $INST_SCRIPTS/download_clion.sh


COPY ./src/ubuntu/install/jetbrains $INST_SCRIPTS
RUN  bash $INST_SCRIPTS/install_clion.sh 

 





USER 1000
